// Nombres en español de las entidades más conocidas; el resto conserva el original del dataset.
const NAMES: Record<string, string> = {
  "Roman Empire": "Imperio romano",
  "Eastern Roman Empire": "Imperio bizantino",
  "Byzantine Empire": "Imperio bizantino",
  "Holy Roman Empire": "Sacro Imperio Romano Germánico",
  "Frankish Kingdom": "Reino franco",
  "Mongol Empire": "Imperio mongol",
  "Chagatai Khanate": "Kanato de Chagatai",
  Ilkhanate: "Iljanato",
  "Khanate of the Golden Horde": "Horda de Oro",
  "Great Khanate": "Gran Kanato (dinastía Yuan)",
  "White Horde": "Horda Blanca",
  "Nogai Horde": "Horda de Nogái",
  "Inca Empire": "Imperio inca",
  "Aztec Empire": "Imperio azteca",
  "Ottoman Empire": "Imperio otomano",
  "Russian Empire": "Imperio ruso",
  "Grand Duchy of Moscow": "Gran Ducado de Moscú",
  "Tsardom of Muscovy": "Zarato ruso",
  Russia: "Rusia",
  USSR: "URSS",
  Spain: "España",
  Portugal: "Portugal",
  France: "Francia",
  "United Kingdom": "Reino Unido",
  England: "Inglaterra",
  Netherlands: "Países Bajos",
  Italy: "Italia",
  Belgium: "Bélgica",
  Denmark: "Dinamarca",
  "Denmark-Norway": "Dinamarca-Noruega",
  "Kalmar Union": "Unión de Kalmar",
  Prussia: "Prusia",
  "German Empire": "Imperio alemán",
  Germany: "Alemania",
  "Austrian Empire": "Imperio austriaco",
  "Austro-Hungarian Empire": "Imperio austrohúngaro",
  "Empire of Japan": "Imperio del Japón",
  Japan: "Japón",
  USA: "Estados Unidos",
  "United States of America": "Estados Unidos",
  Canada: "Canadá",
  Mexico: "México",
  Brazil: "Brasil",
  "Kingdom of Brazil": "Reino de Brasil",
  Colombia: "Colombia",
  Argentina: "Argentina",
  "Viceroyalty of New Spain": "Virreinato de Nueva España",
  "Viceroyalty of New Granada": "Virreinato de la Nueva Granada",
  "Viceroyalty of Peru": "Virreinato del Perú",
  "Viceroyalty of the Río de la Plata": "Virreinato del Río de la Plata",
  "Rupert's Land": "Tierra de Rupert",
  "British East India Company": "Compañía Británica de las Indias Orientales",
  "British Raj": "India británica",
  "Dutch East Indies": "Indias Orientales Neerlandesas",
  "Netherlands Indies": "Indias Orientales Neerlandesas",
  "French West Africa": "África Occidental Francesa",
  "French Equatorial Africa": "África Ecuatorial Francesa",
  "Belgian Congo": "Congo Belga",
  "Qing Empire": "Imperio Qing (China)",
  "Manchu Empire": "Imperio manchú (Qing)",
  "Ming Chinese Empire": "Imperio Ming (China)",
  "Ming Empire": "Imperio Ming (China)",
  "Han Empire": "Imperio Han (China)",
  Han: "Imperio Han (China)",
  "Tang Empire": "Imperio Tang (China)",
  "Song Empire": "Imperio Song (China)",
  "Sui Empire": "Imperio Sui (China)",
  "Jin Empire": "Imperio Jin (China)",
  China: "China",
  "Mughal Empire": "Imperio mogol",
  "Maurya Empire": "Imperio maurya",
  "Gupta Empire": "Imperio Gupta",
  "Kushan Empire": "Imperio kushán",
  "Sultanate of Delhi": "Sultanato de Delhi",
  "Maratha Confederacy": "Confederación maratha",
  "Achaemenid Empire": "Imperio aqueménida (Persia)",
  "Empire of Alexander": "Imperio de Alejandro Magno",
  "Seleucid Kingdom": "Imperio seléucida",
  "Parthian Empire": "Imperio parto",
  "Sasanian Empire": "Imperio sasánida",
  "Safavid Empire": "Imperio safávida",
  "Timurid Empire": "Imperio timúrida",
  "Timurid Emirates": "Emiratos timúridas",
  "Tibetan Empire": "Imperio tibetano",
  "Abbasid Caliphate": "Califato abasí",
  "Umayyad Caliphate": "Califato omeya",
  "Rashidun Caliphate": "Califato ortodoxo",
  Carthage: "Cartago",
  Egypt: "Egipto",
  Persia: "Persia",
  Arabia: "Arabia",
  Antarctica: "Antártida",
  Greenland: "Groenlandia",
};

/** Potencias con colonias o vasallos: el grupo completo recibe nombre de imperio. */
const EMPIRES: Record<string, string> = {
  "United Kingdom": "Imperio británico",
  England: "Inglaterra y sus posesiones",
  Spain: "Imperio español",
  Portugal: "Imperio portugués",
  Netherlands: "Imperio neerlandés",
  Russia: "Imperio ruso",
  USSR: "URSS",
  Italy: "Italia y sus colonias",
  Belgium: "Bélgica y sus colonias",
  Denmark: "Dinamarca y sus territorios",
  "Denmark-Norway": "Dinamarca-Noruega y sus territorios",
  USA: "Estados Unidos y sus territorios",
  China: "China y sus dependencias",
};

export function esName(name: string, year: number, isGroup: boolean): string {
  if (isGroup) {
    if (name === "France") return year < 1500 ? "Reino de Francia y sus feudos" : "Imperio colonial francés";
    if (EMPIRES[name]) return EMPIRES[name];
    const es = NAMES[name] ?? name;
    return /imperio|califato|kanato|urss/i.test(es) ? es : `${es} y sus dependencias`;
  }
  return NAMES[name] ?? name;
}

// Pueblos y culturas sin estado: el dataset los dibuja, pero no son comparables con un país
const PEOPLE =
  /hunter|gatherer|farmers|nomad|pastoral|peoples|tribes|cultures?$|^bantu$|khoisan|austronesians|semites|siberians|inuit|thule|tupis|touareg|tuareg|berber|ainus|chukchi|athaba|uyghurs?$|^mongols$|oghuz|andronovo|karasuk|scythians|proto-|^thai$|dënéndeh|očhéthi|t'atsaot'ine|michif|islamic and hindu states|central asian khanates|warlords|manioc|bison|arctic|pampas|mesoamerican|antarctica|aboriginal/i;

export const isPeople = (name: string) => PEOPLE.test(name);
